spring:
  datasource:
    url:  jdbc:postgresql://localhost:49153/postgres
    username: postgres
    password: postgrespw
  jpa:
    hibernate:
      ddl-auto: update
      #dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect